### ISSUE TITLE
Unavailability isn't implemented in the backend

### ISSUE THREAD

**Issue by amo929** [revaturelabs/assignforce-client#226]
Unavailability represents the "unavailability" of a trainer by subtracting the current date and a trainer's current batch endDate (my assumption). 
This has a direct relationship with the 'Settings' page option of "Minimum Day Between Trainer Batches", and when creating a new batch.
So the cases are:
- If the trainer is in a batch, the trainer is considered **unavailable**.
- If the trainer has concluded a batch but is still within the time frame of "Minimum Day Between Trainers Batches", then the trainer is considered **unavailable.**
- If the trainer is inactive, the trainer is considered **unavailable** or the trainer's name is not even displayed when creating a batch.
- If none of the above conditioned are fulfilled, then the trainer is considered **available.**

**Comment by tjansen17** [comment]
Trainer object in trainer service now contains a set of unavailabilities which are persisted in the db.

-T
