### ISSUE TITLE
The navbar switches between two tabs infinitely after switching quickly between tabs

### ISSUE THREAD

**Issue by amo929** [revaturelabs/assignforce-client#230]
Bug discovered on a Localhost environment.
Sometimes, after redirecting to another page, your navbar will route between two pages continuously. 
Could not reproduce the problem, it sometimes appears to happen when you switch between tabs too quickly.

**Comment by MosesExe** [comment]
Reproduced by clicking between tabs rapidly, causing an infinite load between both tabs. Solution being worked on with possibility of just creating a new navbar being the solution.

**Comment by MosesExe** [comment]
Also fixes logout bug which was tied to the navbar for some reason

**Comment by dgriss** [comment]
Fixed this bug while working on #266

**Comment by dgriss** [comment]
Going to make another issue for the log out bug just so we have record of it
