### ISSUE TITLE
Gateway Auth0 unverified. Gateway testing fails if authentication is present

### ISSUE THREAD

**Issue by tjansen17** [revaturelabs/assignforce-client#237]
For now, past authentication is being commented out for testing of all services.
Will approach later

**Comment by fireflyoc** [comment]
Auth0 *should* (untested as of now) work once the front and back end are connected.  The JWT tokens are being correctly generated on the front end and are being passed to the back.  This issue seems related to #279 (Something to do with SSL certification).

**Comment by falenas108** [comment]
Works!
