### ISSUE TITLE
Need to delete unavailability service.

### ISSUE THREAD

**Issue by tjansen17** [revaturelabs/assignforce-client#246]
AvailabilityService is not needed

**Comment by sygmo** [comment]
Why was I assigned to this issue?

**Comment by mfboulos** [comment]
Labelled this as a suggestion, seems to only need to go up to leadership level of the group in charge of the backend so I'm assigning it back to @tjansen17 to close it whenever the decision is resolved.

**Comment by tjansen17** [comment]
Unavailability is enclosed in the trainer service
