### ISSUE TITLE
Combining address, building, and rooms into a single location service

### ISSUE THREAD

**Issue by tjansen17** [revaturelabs/assignforce-client#252]
update the model so that each address with hold a building collection, and each building will hold a collection of rooms.

- [x] update model in database
- [x] update model in angular

**Comment by falenas108** [comment]
Address has a field called "active", should to changed to "isActive"
Address should contain an array of buildings
Buildings have a field called "active", should be changed to "isActive"
Buildings have an array of numbers called "rooms", should be changed to an array of rooms
Address has a field called "active", should to changed to "isActive"
Rooms should not have a building object, buildings have room objects.
Rooms have a field called "unavailabilities, should be deleted".
