### ISSUE TITLE
Can add Trainers with same email

### ISSUE THREAD

**Issue by MosesExe** [revaturelabs/assignforce-client#262]
Issue being that there's no validation check to see if an email is already registered with a trainer (or in the testing case the test.trainer) the "new" trainers profile will always default to the first profile made

It's an issue we shouldn't logically run into as no one get's their account from the website, but it cant hurt to have it later in case

**Comment by dgriss** [comment]
Fixed by adding some code to the trainer's component and adding a new component(AddTrainerError) to trainers to open as a dialog box when a trainer with the same email is trying to be added. The dialog box is simple with a few elements and some text giving you an error message
