### ISSUE TITLE
Set up fully functioning DevOps pipeline

### ISSUE THREAD

**Issue by mfboulos** [revaturelabs/assignforce-client#269]

**Comment by neuroleptic** [comment]
There is currently Jenkins running on an EC2 instance that automatically builds and deploys all of the microservices to a remote EC2 server as docker containers. There is also integration with SonarQube to check for static code analysis.

The next step is to integrate JUnit testing into the build lifecycle.

**Comment by neuroleptic** [comment]
JUnit and JaCoCo have been integrated into the pipeline. SonarQube now displays statistics about code coverage from JaCoCo.
