### ISSUE TITLE
New Nav-bar won't go to profile

### ISSUE THREAD

**Issue by MosesExe** [revaturelabs/assignforce-client#275]
Refactored nav-bar won't take you to the profile page. 

I went into the menubar.ts and changed the url since it was pointing to trainers instead of profile for some reason. Now after changing it will only take you to the overview page.

**Comment by dgriss** [comment]
Fixed this bug by getting the profile of the logged in user from Auth0 which contains their email and then appending that to the path variable in the tabs object. so that the path is /profile/[useremail] which properly navigates to the profile page for the logged in user
