### ISSUE TITLE
Locations without a given City and State still have a comma to separate the null entries

### ISSUE THREAD

**Issue by mfboulos** [revaturelabs/assignforce-client#284]
In the Locations tab, each Location has a superscript representation "city, state" of where it's location. If those entries are null, it still displays a comma, which should not be the case. The fix would involve a simple check for nulls and omitting that comma if either city or state is null.

**Comment by Jentoft** [comment]
I put the comma and space in a span and used *ngIf to only display it when both city and state are not null

**Comment by mfboulos** [comment]
Fix still not merged to dev branch as of pull request #295. Please close this bug once the fix is merged.
