### ISSUE TITLE
Cannot access Trainer profile for trainers that have no skills

### ISSUE THREAD

**Issue by mfboulos** [revaturelabs/assignforce-client#285]
Clicking a trainer in the Trainers tab should open a profile with information about them. It seems that is only possible for trainers with skills listed, even though the profile information is not limited to skills alone.

**Comment by fireflyoc** [comment]
Trainer profiles are accessed via their email, of which only 2 trainers have in the db.json file.  Will need to add each trainers' email in the database or change the profile to be accessed by a trainer id (dependent on back-end support for a get by Id method).

**Comment by fireflyoc** [comment]
Because the trainer profile is accessed via email, the users' email is stored in the access JWT token, therefore, the profile can't be accessed via ID without changing the access token.  Again, once the database is fully populated this won't be an issue.
