### ISSUE TITLE
Permission levels are cached for Profile tab visibility

### ISSUE THREAD

**Issue by mfboulos** [revaturelabs/assignforce-client#290]
The Profile tab should be unviewable by the SVP, since the Profile is trainer-specific and the SVP is inherently not a trainer. However, it is viewable when directly logging out from a trainer account and into the SVP account in the same session. A similar issue occurs in the opposite direction: when switching from the SVP account to a trainer, the Profile tab is no longer visible to the trainer.

An easy workaround is to refresh the page, it then refreshes the tabs and shows/hides the tabs appropriately.

**Comment by MosesExe** [comment]
Working on it

**Comment by dgriss** [comment]
This issue has been fixed in doing #266
