### ISSUE TITLE
Batch Timeline bugs out if value is removed from TrainersPerPage

### ISSUE THREAD

**Issue by Jshellab** [revaturelabs/assignforce-client#292]
If no value is entered in the TrainersPerPage box after previously containing a value, the table bugs out and cannot be used unless refreshed or a large number is entered. Leaving the box with no entry should return the table to its original format.

This bug can be reproduced by entering a value in the TrainersPerPage box, then removing it.

**Comment by DragonLotus** [comment]
Fixed with https://github.com/revaturelabs/assignforce-client/commit/a581a988801adf7f033ad0f4072ef2cbcdf0831e under Timeline feature.
