### ISSUE TITLE
Clean-up time! Comments and console.logs will be purged.

### ISSUE THREAD

**Issue by sygmo** [revaturelabs/assignforce-client#345]
Also includes small adjustments for readability. Only comments deemed unnecessary will be deleted.

**Comment by sygmo** [comment]
We can leave a few console.logs if we feel they will be useful to the next branch (any suggestions?), but the code should look as clean and completed as possible.

**Comment by mfboulos** [comment]
Components are cleaned of any unused functions and extraneous console logs. Any logs regarding error messages have been left for debugging purposes.

**Comment by BudhiChristian** [comment]
Everybody did their share!
