### ISSUE TITLE
Button to delete batch on batch tab needs to be clicked twice to delete it

### ISSUE THREAD

**Issue by tjansen17** [revaturelabs/assignforce-client#348]
To delete a batch on the batch tab, the delete button needs to be clicked twice.

**Comment by tulipanh** [comment]
This looks like it might be an issue with asynchronous operations. The deleteBatch method is called sending a delete request via BatchService. Immediately after, the refreshBatches method called without waiting for any confirmation that the deletion was executed on the back end. The refresh operation should be delayed until the delete operation completes. I'm not sure how you would do this with the way the service is currently set up.

**Comment by falenas108** [comment]
Fixed!  It's now an observable that can be subscribed to.
